### ISSUE TITLE
[Suggestion] Ajouter une checkbox dans le line chart ELO

### ISSUE THREAD

**Issue by clablancherie-devalto** [clesquir/js-volemon#157]
Quand on veut voir son évolution niveau graphique, c'est chiant car on ne peut pas se sélectionner directement.
Ça serait cool d'avoir un bouton, lien ou que sais-je avec inscrit "Voir mes stats"

**Comment by clesquir** [comment]
In fact, in the end, I would like to modify this page to allow a manual selection of the users you want to appear in the chart. Although, the ELO line chart would be nice for the current user indeed. I will add it to the list of issues.
